Description: Compute Resources

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  VPC:
    Description: A reference to the VPC created in the network stack
    Type: AWS::EC2::VPC::Id
  PublicSubnet:
    Description: A reference to the public subnet created in the network stack
    Type: AWS::EC2::Subnet::Id

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${EnvironmentName}-ECSCluster

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP/HTTPS traffic
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet
      Type: application

  # ... (Define other compute resources like Auto Scaling groups, target groups, etc.)

Outputs:
  ECSCluster:
    Description: A reference to the created ECS cluster
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${EnvironmentName}-ECSCluster

  ALB:
    Description: A reference to the created ALB
    Value: !Ref ALB
    Export:
      Name: !Sub ${EnvironmentName}-ALB