version: 0.0
os: linux
files:
  - source: /
    destination: /var/app/current/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build_frontend.sh
      timeout: 300
      runas: root
    - location: scripts/build_backend.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root